name: ⚗️ ConfettiKit CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 💆‍♀️ Build ConfettiKit
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Check out repository
        uses: actions/checkout@v6

      - name: 🍉 Configure JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: 🔨 Build project
        run: ./gradlew assemble

  test-desktop:
    name: 🖥️ Test Desktop
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🛎️ Check out repository
        uses: actions/checkout@v6

      - name: 🍉 Configure JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: 🧪 Run JVM Tests
        run: ./gradlew jvmTest

  test-android:
    name: 🤖 Test Android
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Check out repository
        uses: actions/checkout@v6

      - name: 🍉 Configure JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: 🧪 Run Android Unit Tests
        run: ./gradlew testAndroidHostTest

  test-ios:
    name: 🍎 Test iOS
    needs: build
    runs-on: macos-latest
    steps:
      - name: 🛎️ Check out repository
        uses: actions/checkout@v6

      - name: 🍉 Configure JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: 🧪 Run iOS Tests
        run: ./gradlew iosSimulatorArm64Test
